name: Bug
description: Report a bug
title: "[BUG]: "
labels: ["bug"]
body:
  - type: input
    id: parent_issue
    attributes:
      label: Parent Issue Number (Task or Feature)
      description: Enter the issue number of the parent task or feature (e.g., 12). Leave empty if standalone.
      placeholder: "12"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.
    validations:
      required: true
